export const interests: string[] = [
    'Adventure Seeker',
    'Animal Lover',
    'Art Lover',
    'Bookworm',
    'Coffee Lover',
    'Fitness Enthusiast',
    'Foodie',
    'Gamer',
    'Movie Buff',
    'Music Lover',
    'Nature Lover',
    'Outdoor Explorer',
    'Pet Owner',
    'Photography Enthusiast',
    'Traveler',
    'Tech Geek',
    'Yoga & Meditation',
    'Sports Fan',
    'Fashionista',
    'Hiker',
    'Dancing',
    'Cooking',
    'Sports & Fitness',
    'Party Animal',
    'Creative Writer',
    'History Buff',
    'Social Activist',
    'Netflix Binger',
    'Food Blogger',
    'Entrepreneur',
    'Volunteer',
    'Fashion Lover',
    'Hobbyist',
    'Singer',
    'Art & Craft',
    'Film Geek',
    'Fashion & Style',
    'Gardening',
    'DIY Enthusiast',
    'Comedy Fan',
    'Theater Lover',
    'Cars & Bikes',
    'Anime Fan',
    'Astronomy Geek',
    'Business Professional',
    'Collectibles',
    'Cycling',
    'Health & Wellness',
    'Musician',
    'Night Owl',
    'Early Riser',
    'Tech Enthusiast',
    'Wine Connoisseur',
  ];
  